// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Severity.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Logging.Syslog.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Logging.Syslog.Recipes
{
    /// <summary>
    /// Syslog severities.
    /// </summary>
    /// <remarks>
    ///  Adapted from enumeration of same name in <a href="https://github.com/emertechie/SyslogNet"/>.
    /// </remarks>
#if !OBeautifulCodeLoggingRecipesProject
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Logging.Syslog.Recipes", "See package version number")]
    internal
#else
    public
#endif
    enum Severity
    {
        /// <summary>
        /// system is unusable
        /// </summary>
        Emergency = 0,

        /// <summary>
        /// action must be taken immediately
        /// </summary>
        Alert = 1,

        /// <summary>
        /// critical conditions
        /// </summary>
        Critical = 2,

        /// <summary>
        /// error conditions
        /// </summary>
        Error = 3,

        /// <summary>
        /// warning conditions
        /// </summary>
        Warning = 4,

        /// <summary>
        /// normal but significant condition
        /// </summary>
        Notice = 5,

        /// <summary>
        /// informational messages
        /// </summary>
        Informational = 6,

        /// <summary>
        /// debug-level messages
        /// </summary>
        Debug = 7,
    }
}
