// --------------------------------------------------------------------------------------------------------------------
// <copyright file="LogglySettings.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Logging source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Logging.Recipes
{
    /// <summary>
    /// Loggly settings.
    /// </summary>
#if !OBeautifulCodeLoggingRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Logging", "See package version number")]
    internal
#else
    public
#endif
    class LogglySettings
    {
        /// <summary>
        /// Gets or sets the Loggly customer token.
        /// </summary>
        public string CustomerToken { get; set; }

        /// <summary>
        /// Gets or sets the Loggly server certificate, PEM-encoded.
        /// </summary>
        /// <remarks>
        /// <code>
        /// Get the .crt file using the URL here: <a href="https://www.loggly.com/docs/upgrade-tls-certificate/"/>
        /// Run this command: openssl x509 -in CRT_FILE_PATH -out NEW_PEM_FILE_PATH -outform PEM
        /// Use this tool to convert to JSON string: <a href="https://www.freeformatter.com/json-escape.html" />
        /// </code>
        /// </remarks>
        public string LogglyServerCertificatePemEncoded { get; set; }

        /// <summary>
        /// Gets or sets the Loggly private enterprise number.
        /// </summary>
        public string LogglyPrivateEnterpriseNumber { get; set; } = "41058";

        /// <summary>
        /// Gets or sets the Loggly syslog server.
        /// </summary>
        public string SyslogServer { get; set; } = "logs-01.loggly.com";

        /// <summary>
        /// Gets or sets the port to use for secure traffic.
        /// </summary>
        public int SecurePort { get; set; } = 6514;

        /// <summary>
        /// Gets or sets the syslog facility name to send messages as.
        /// </summary>
        public Facility Facility { get; set; } = Facility.Local0;
    }
}
